# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4613caeb769a438a9a1352b593eec4a3f3c4497bea16cc1ab685dbf21655d0061f5f963119f97e5fbdf8e48d1c59ded76dc8265688fdea7cc1c5918a50a20fc6

test:
  secret_key_base: d2ebd4e69e288b008a93afee5cce3d556f0e49e2a8b2af32c6e86a1c1cf0a385b0f9dc781f21b92a1e8a9742fd3c66e5f1224f9baedcaf037859228da4b12ed8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
